# Generated by Django 3.1.7 on 2021-05-25 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('Rajshahi', 'Rajshahi'), ('Dhaka', 'Dhaka'), ('Chattogram', 'Chattogram'), ('Sylhet', 'Sylhet'), ('Khulna', 'Khulna'), ('Rangpur', 'Rangpur'), ('Barisal', 'Barisal'), ('Mymensingh', 'Mymensingh')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('M', 'Mobile'), ('l', 'Laptop'), ('TW', 'TopWears'), ('BM', 'Bottomwears')], max_length=50)),
                ('product_image', models.ImageField(upload_to='product_image')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Rajshahi', 'Rajshahi'), ('Dhaka', 'Dhaka'), ('Chattogram', 'Chattogram'), ('Sylhet', 'Sylhet'), ('Khulna', 'Khulna'), ('Rangpur', 'Rangpur'), ('Barisal', 'Barisal'), ('Mymensingh', 'Mymensingh')], default='Pending', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
